baseURL = "https://jorgesilvadesign.github.io/"
languageCode = "en-us"
title = "Jorge Silva"
theme = "PaperMod"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
